### ISSUE TITLE
ClearTokens() not implemented

### ISSUE THREAD

**Issue by ghost** [Volue/Powel.AzureTableStorage.IdentityServer4#1]
Hi,

thanks for providing this persistence layer! Is there a reason the code in TokenCleanup::ClearTokens is commented out?

thanks!

**Comment by torhovland** [comment]
Hi!

No particular reason except I didn't get around to fixing a working implementation. You're welcome to submit a pull request!

I should emphasize that this package only stores persisted grants, not configuration or users. If you need user persistence in Table Storage, you might want to look at https://dlmelendez.github.io/identityazuretable

**Comment by ghost** [comment]
thanks and yes I'm aware of that, I'm using it for the persisted grants only. I played around with identityazuretable but ended up in creating a simple own table user store and profile because I didn't want to use asp.net identity. 

I'll have a look at it if I get time! One thing that already causes me headaches is that this table can be potentially huge depending on the application and that the search for entities with Expiration < Now can be quite expensive.

**Comment by torhovland** [comment]
OK.

By the way, I came to the same conclusion regarding a persisted user store in Table Storage :-)
